language: minimal

env:
- HUGO_VERSION=0.54.0

before_install:
- mkdir -p bin
- curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o bin/hugo.tar.gz
- tar xzvvf bin/hugo.tar.gz -C ./bin

# Clean and don't fail
install:
  - rm -rf public || exit 0

script:
- "./bin/hugo"

deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_AUTH_SECRET
  on:
    branch: master
