baseURL = "http://example.org/"
languageCode = "en-us"
title = "TICS website"

theme = "mondrian"
# Theme config
[taxonomies]
  tag = "tags"

[params]
  showHeader = true
  showTags = true
  debug = false
  [params.colors]
    post = "orangered"
    posts = "gold"
    page = "#cb0713"
    sketch = "limegreen"


#[menu]
#  [[menu.main]]
#    name = "previous editions"
#    url = "/past"
#    weight = 1
