baseURL = "http://example.org/"
languageCode = "en-us"
title = "TICS website"

theme = "mondrian"
# Theme config
[taxonomies]
  tag = "tags"

[params]
  showHeader = true
  showTags = true
  debug = false
  [params.colors]
    post = "orangered"
    posts = "gold"
    page = "blue"
    sketch = "limegreen"


[menu]
  [[menu.main]]
    name = "previous editions"
    url = "/past"
    weight = 1
#  [[menu.main]]
#    name = "about"
#    url = "/about"
#    weight = 2
